export const insightsTranslations = {
  fr: {
    insights: "Insights", seeInsights: "Voir les Insights", back: "Retour au tableau de bord", mainInsight: "Insight",
    semesterAnalysis: "Analyse du semestre", currentAverage: "Moyenne actuelle", globalTrend: "Tendance globale", stabilityLabel: "Stabilité", simulatedAbove: "Moyenne ≥ 5", simulatedCompensation: "Compensation GBJB",
    mainInsights: "Insights principaux", subjectTrends: "Tendances par matière", simulation: "Simulation du semestre", simulationInfo: "Les probabilités sont estimées à partir de milliers de scénarios générés selon les résultats précédents (méthode de Monte-Carlo).",
    simulationSettings: "Paramètres de simulation", remaining: "Évaluations restantes", expectedCoefficient: "Coefficient moyen attendu", run: "Mettre à jour la simulation", simulations: "10 000 simulations locales", likelyAverage: "Moyenne finale probable", median: "Médiane", simulatedProbability: "Probabilité simulée", compensationProbability: "Compensation", belowProbability: "Au moins une branche sous 4", riskySubjects: "Matières les plus à risque", assumptions: "Ces résultats dépendent des hypothèses utilisées pour générer les futures notes.",
    noData: "Ajoute des notes incluses au bulletin pour obtenir des analyses.", confidence: "Confiance", confidence_low: "faible", confidence_medium: "moyenne", confidence_high: "élevée", insufficient: "Données insuffisantes", stable: "stable", slight_up: "légère progression", strong_up: "forte progression", slight_down: "légère baisse", strong_down: "forte baisse", volatility_stable: "très régulière", volatility_variable: "variable", volatility_high: "très variable",
    trend_up: { title: "Progression en {subject}", description: "La tendance de tes résultats récents est positive sur l’ensemble des notes disponibles." }, trend_down: { title: "Baisse à surveiller en {subject}", description: "La tendance calculée sur plusieurs résultats est orientée à la baisse." },
    anomaly_low: { title: "Résultat récent atypique en {subject}", description: "La dernière note est nettement sous les résultats habituels ; elle peut être atypique plutôt qu’indiquer une tendance." }, anomaly_high: { title: "Résultat récent atypique en {subject}", description: "La dernière note est nettement au-dessus des résultats habituels ; les prochaines notes diront si cela se confirme." },
    stability: { title: "Résultats réguliers en {subject}", description: "Les notes sont peu dispersées et indiquent une bonne régularité." }, volatility: { title: "Résultats variables en {subject}", description: "Les notes sont assez dispersées ; la moyenne peut donc évoluer davantage." }, risk: { title: "Seuil à surveiller en {subject}", description: "La moyenne actuelle est sous le seuil suisse de 4." }, leverage: { title: "Levier mathématique : {subject}", description: "Avec les coefficients actuels, une prochaine note améliorée de 0,5 point aurait ici le plus d’effet sur la moyenne générale." },
    compensation_fragile: { title: "Compensation actuellement fragile", description: "La règle GBJB est respectée, mais avec une marge mathématique limitée." }, compensation_comfortable: { title: "Compensation actuellement confortable", description: "Les points positifs couvrent le double des points négatifs avec une marge." }, compensation_risk: { title: "Compensation à surveiller", description: "Les points positifs ne couvrent pas actuellement le double des points négatifs." }, compensation_negative: { title: "Points négatifs : {subject}", description: "Cette matière génère actuellement la plus grande contribution négative à la compensation." }, compensation_positive: { title: "Points positifs : {subject}", description: "Cette matière apporte actuellement la plus grande contribution positive à la compensation." },
  },
  en: {
    insights: "Insights", seeInsights: "View Insights", back: "Back to dashboard", mainInsight: "Insight", semesterAnalysis: "Semester analysis", currentAverage: "Current average", globalTrend: "Overall trend", stabilityLabel: "Stability", simulatedAbove: "Average ≥ 5", simulatedCompensation: "GBJB compensation", mainInsights: "Main insights", subjectTrends: "Trends by subject", simulation: "Semester simulation", simulationInfo: "Probabilities are estimated from thousands of scenarios generated from previous results (Monte Carlo method).", simulationSettings: "Simulation settings", remaining: "Remaining assessments", expectedCoefficient: "Expected average coefficient", run: "Update simulation", simulations: "10,000 local simulations", likelyAverage: "Likely final average", median: "Median", simulatedProbability: "Simulated probability", compensationProbability: "Compensation", belowProbability: "At least one subject below 4", riskySubjects: "Subjects most at risk", assumptions: "These results depend on the assumptions used to generate future grades.", noData: "Add report-card grades to receive analyses.", confidence: "Confidence", confidence_low: "low", confidence_medium: "medium", confidence_high: "high", insufficient: "Not enough data", stable: "stable", slight_up: "slight improvement", strong_up: "strong improvement", slight_down: "slight decline", strong_down: "strong decline", volatility_stable: "very consistent", volatility_variable: "variable", volatility_high: "highly variable",
    trend_up: { title: "Improvement in {subject}", description: "The trend across the available grades is positive." }, trend_down: { title: "Decline to watch in {subject}", description: "The trend calculated over several results is moving down." }, anomaly_low: { title: "Unusual recent result in {subject}", description: "The latest grade is well below the usual results; it may be atypical rather than a trend." }, anomaly_high: { title: "Unusual recent result in {subject}", description: "The latest grade is well above the usual results; future grades will show whether it continues." }, stability: { title: "Consistent results in {subject}", description: "Grades have little dispersion and indicate good consistency." }, volatility: { title: "Variable results in {subject}", description: "Grades are dispersed, so the average may change more." }, risk: { title: "Threshold to watch in {subject}", description: "The current average is below the Swiss threshold of 4." }, leverage: { title: "Mathematical lever: {subject}", description: "With current coefficients, improving the next grade by 0.5 would have the greatest effect here." }, compensation_fragile: { title: "Compensation is currently fragile", description: "The GBJB rule is met, but with a limited mathematical margin." }, compensation_comfortable: { title: "Compensation is currently comfortable", description: "Positive points cover twice the negative points with a margin." }, compensation_risk: { title: "Compensation needs attention", description: "Positive points do not currently cover twice the negative points." }, compensation_negative: { title: "Negative points: {subject}", description: "This subject currently makes the largest negative contribution to compensation." }, compensation_positive: { title: "Positive points: {subject}", description: "This subject currently makes the largest positive contribution to compensation." },
  },
  de: {
    insights: "Insights", seeInsights: "Insights ansehen", back: "Zurück zur Übersicht", mainInsight: "Insight", semesterAnalysis: "Semesteranalyse", currentAverage: "Aktueller Durchschnitt", globalTrend: "Gesamttrend", stabilityLabel: "Stabilität", simulatedAbove: "Durchschnitt ≥ 5", simulatedCompensation: "GBJB-Kompensation", mainInsights: "Wichtigste Insights", subjectTrends: "Trends nach Fach", simulation: "Semestersimulation", simulationInfo: "Die Wahrscheinlichkeiten werden aus Tausenden von Szenarien geschätzt, die anhand bisheriger Ergebnisse erzeugt werden (Monte-Carlo-Methode).", simulationSettings: "Simulationseinstellungen", remaining: "Verbleibende Prüfungen", expectedCoefficient: "Erwarteter Durchschnittskoeffizient", run: "Simulation aktualisieren", simulations: "10.000 lokale Simulationen", likelyAverage: "Wahrscheinlicher Enddurchschnitt", median: "Median", simulatedProbability: "Simulierte Wahrscheinlichkeit", compensationProbability: "Kompensation", belowProbability: "Mindestens ein Fach unter 4", riskySubjects: "Fächer mit dem größten Risiko", assumptions: "Diese Ergebnisse hängen von den Annahmen zur Erzeugung künftiger Noten ab.", noData: "Füge zeugnisrelevante Noten hinzu, um Analysen zu erhalten.", confidence: "Vertrauen", confidence_low: "niedrig", confidence_medium: "mittel", confidence_high: "hoch", insufficient: "Zu wenig Daten", stable: "stabil", slight_up: "leichte Verbesserung", strong_up: "starke Verbesserung", slight_down: "leichter Rückgang", strong_down: "starker Rückgang", volatility_stable: "sehr regelmäßig", volatility_variable: "variabel", volatility_high: "stark variabel",
    trend_up: { title: "Fortschritt in {subject}", description: "Der Trend über die verfügbaren Noten ist positiv." }, trend_down: { title: "Rückgang in {subject} beobachten", description: "Der über mehrere Ergebnisse berechnete Trend zeigt nach unten." }, anomaly_low: { title: "Ungewöhnliches Ergebnis in {subject}", description: "Die letzte Note liegt deutlich unter dem Üblichen; sie kann ein Ausreißer statt eines Trends sein." }, anomaly_high: { title: "Ungewöhnliches Ergebnis in {subject}", description: "Die letzte Note liegt deutlich über dem Üblichen; weitere Noten zeigen, ob das anhält." }, stability: { title: "Regelmäßige Ergebnisse in {subject}", description: "Die Noten streuen wenig und weisen auf gute Konstanz hin." }, volatility: { title: "Variable Ergebnisse in {subject}", description: "Die Noten streuen, daher kann sich der Durchschnitt stärker verändern." }, risk: { title: "Grenzwert in {subject} beobachten", description: "Der aktuelle Durchschnitt liegt unter der Schweizer Bestehensgrenze 4." }, leverage: { title: "Mathematischer Hebel: {subject}", description: "Mit den aktuellen Koeffizienten hätte eine um 0,5 bessere nächste Note hier den größten Effekt." }, compensation_fragile: { title: "Kompensation derzeit knapp", description: "Die GBJB-Regel ist erfüllt, aber mit geringer mathematischer Marge." }, compensation_comfortable: { title: "Kompensation derzeit komfortabel", description: "Positive Punkte decken die doppelten negativen Punkte mit Reserve." }, compensation_risk: { title: "Kompensation beobachten", description: "Positive Punkte decken derzeit nicht die doppelten negativen Punkte." }, compensation_negative: { title: "Negative Punkte: {subject}", description: "Dieses Fach trägt derzeit am stärksten negativ zur Kompensation bei." }, compensation_positive: { title: "Positive Punkte: {subject}", description: "Dieses Fach trägt derzeit am stärksten positiv zur Kompensation bei." },
  },
};

export const interpolate = (text, values = {}) => String(text || "").replace(/\{(\w+)\}/g, (_, key) => values[key] ?? "");
