import { useMemo, useState } from "react";
import { formatGrade } from "@/components/grades/gradeUtils";
import { usableNotes } from "@/lib/analytics/statistics";

export default function GradeHeatmap({ notes, gradingSystem, language, t }) {
  const [selected, setSelected] = useState(null);
  const groups = useMemo(() => Object.entries(Object.groupBy(usableNotes(notes).filter((note) => /^\d{4}-\d{2}-\d{2}/.test(String(note.date || ""))), (note) => note.date.slice(0, 7))).sort(([a],[b]) => a.localeCompare(b)), [notes]);
  const locale = language === "de" ? "de-CH" : language === "en" ? "en-GB" : "fr-CH";
  return <section className="neu-card"><h2 className="text-xl font-bold text-slate-700">{t.heatmap}</h2><p className="text-xs text-slate-500 mt-1 mb-5">{t.incomplete}</p>{!groups.length ? <p className="text-slate-500">{t.noDated}</p> : <div className="space-y-5">{groups.map(([month, monthNotes]) => <div key={month}><h3 className="mb-2 text-sm font-semibold capitalize text-slate-600">{new Date(`${month}-02T12:00:00`).toLocaleDateString(locale,{month:"long",year:"numeric"})}</h3><div className="flex flex-wrap gap-2">{monthNotes.sort((a,b)=>a.date.localeCompare(b.date)).map((note,index)=>{const level=Math.max(0,Math.min(4,Math.floor((Number(note.note)-1)/1.25))); return <button key={note.id || `${note.date}-${index}`} onClick={()=>setSelected(note)} aria-label={`${note.date}, ${note.matiere}, ${formatGrade(note.note,gradingSystem)}`} title={`${note.date} · ${note.matiere} · ${formatGrade(note.note,gradingSystem)}`} className="h-11 min-w-11 rounded-lg px-2 text-xs font-bold text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-700" style={{backgroundColor:["#9f1239","#be123c","#b45309","#0f766e","#475569"][level]}}>{formatGrade(note.note,gradingSystem)}</button>})}</div></div>)}</div>}<div aria-live="polite" className="mt-5 rounded-xl bg-slate-700/5 p-4 text-sm text-slate-600">{selected ? <><p className="font-bold text-slate-700">{new Date(`${selected.date}T12:00:00`).toLocaleDateString(locale,{dateStyle:"long"})}</p><p>{selected.matiere} — {selected.nom_evaluation || t.total}</p><p>{formatGrade(selected.note,gradingSystem)} · {t.coefficient} {selected.coefficient > 0 ? selected.coefficient : 1}</p></> : t.selectCell}</div></section>;
}
