import { useMemo } from "react";
import { replayAtDate, replayEvolution } from "@/lib/analytics/history";
import { formatGrade } from "@/components/grades/gradeUtils";

const day = 86400000;
export default function ReplayTimeline({ notes, date, onDateChange, gradingSystem, language, filters={ year: undefined, semester: undefined, archived: undefined }, t, compact=false }) {
  const dates=useMemo(()=>notes.filter(n=>n.date&&!n.exclue_bulletin&&!n.matiere_hors_bulletin&&(!filters.year||filters.year==="all"||n.annee===filters.year)&&(!filters.semester||filters.semester==="all"||n.semestre===filters.semester)&&(typeof filters.archived!=="boolean"||Boolean(n.archived)===filters.archived)).map(n=>n.date).sort(),[notes,filters]); const min=dates[0]; const max=dates.at(-1);
  const effectiveDate=date&&date>=min&&date<=max?date:max; const value=effectiveDate ? Math.round((new Date(`${effectiveDate}T12:00:00`).getTime()-new Date(`${min}T12:00:00`).getTime())/day) : 0; const maxDays=min&&max?Math.max(0,Math.round((new Date(`${max}T12:00:00`).getTime()-new Date(`${min}T12:00:00`).getTime())/day)):0;
  const state=useMemo(()=>effectiveDate?replayAtDate(notes,{...filters,date:effectiveDate}):null,[notes,effectiveDate,filters]); const evolution=useMemo(()=>replayEvolution(notes,filters),[notes,filters]);
  const grade=v=>v==null?"—":formatGrade(v,gradingSystem); const locale=language==="de"?"de-CH":language==="en"?"en-GB":"fr-CH";
  if(!min) return <p className="text-sm text-slate-500">{t.noDated}</p>;
  const selectDate=(next)=>onDateChange(next);
  return <div className="space-y-4"><input aria-label={t.historyDate || t.replay} type="date" min={min} max={max} value={effectiveDate} onChange={e=>selectDate(e.target.value)} className="w-full rounded-xl bg-[#e0e5eb] px-3 py-2 shadow-inner"/><input aria-label={t.replay} type="range" min="0" max={maxDays} value={Math.min(value,maxDays)} onChange={e=>selectDate(new Date(new Date(`${min}T12:00:00`).getTime()+Number(e.target.value)*day).toISOString().slice(0,10))} className="w-full accent-slate-600"/><div className="flex justify-between text-xs text-slate-500"><span>{min}</span><span>{max}</span></div>{evolution.length>1&&<div><p className="text-xs text-slate-500 mb-2">{t.evolution}</p><div className="flex h-16 items-end gap-1" role="img" aria-label={t.evolution}>{evolution.map(point=><button type="button" key={point.date} title={`${point.date}: ${grade(point.average)}`} aria-label={`${point.date}: ${grade(point.average)}`} onClick={()=>selectDate(point.date)} className="min-w-1 flex-1 rounded-t bg-slate-500 focus-visible:ring-2" style={{height:`${Math.max(10,(point.average-1)/5*100)}%`}} />)}</div></div>}{state&&state.count>0?<div className="rounded-xl bg-slate-700/5 p-4"><p className="font-bold text-slate-700">{t.stateAt} {new Date(`${effectiveDate}T12:00:00`).toLocaleDateString(locale)}</p><div className="grid grid-cols-2 gap-2 mt-3 text-sm"><p>{t.average}: <b>{grade(state.average)}</b></p><p>{state.count} {t.count.toLowerCase()}</p><p>{t.compensation}: <b>{state.compensation.margin>=0?"+":""}{state.compensation.margin.toFixed(1)}</b></p><p>{t.positive}: {state.compensation.positiveSum.toFixed(1)}</p>{!compact&&<><p>{t.negative}: {state.compensation.negativeSum.toFixed(1)}</p><p>{t.doubleNegative}: {state.compensation.doubleNegative.toFixed(1)}</p></>}</div><ul className="mt-3 border-t border-slate-300 pt-2 text-sm">{state.subjects.map(item=><li className="flex justify-between" key={item.subject}><span>{item.subject}</span><b>{grade(item.average)}</b></li>)}</ul></div>:<p className="text-sm text-slate-500">{t.historyNoNotes || t.noData}</p>}</div>;
}
