import { useMemo, useState } from "react";
import { Area, AreaChart, Bar, ComposedChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ANALYTICS_CONFIG } from "@/lib/analytics/config";
import { buildPredictiveDistribution } from "@/lib/analytics/monteCarlo";
import { descriptiveStats } from "@/lib/analytics/descriptiveStats";
import { weightedAverage } from "@/lib/analytics/statistics";
import { walkForwardBacktest } from "@/lib/lab/backtesting";
import { bootstrapDistribution } from "@/lib/lab/bootstrap";
import { sensitivityCurve, sensitivityPoint } from "@/lib/lab/sensitivity";
import { formatGrade } from "@/components/grades/gradeUtils";

const Card=({children,className=""})=><section className={`neu-card ${className}`}>{children}</section>;
const Metric=({label,value,title=null})=><div className="rounded-xl bg-slate-700/5 p-3" title={title||undefined}><p className="text-xs text-slate-500">{label}</p><p className="font-bold text-slate-700">{value}</p></div>;
const fmt=v=>Number.isFinite(v)?v.toFixed(2):"—";

export function BacktestingPanel({notes,t}) {
 const subjects=useMemo(()=>[...new Set(notes.map(n=>String(n.matiere).trim()))].sort(),[notes]); const [subject,setSubject]=useState(subjects[0]||""); const [iterations,setIterations]=useState(2000);
 const selected=notes.filter(n=>String(n.matiere).trim()===subject); const result=useMemo(()=>walkForwardBacktest(selected,{iterations,seed:482917}),[selected,iterations]); const primary=result.notesgym;
 return <div className="space-y-5"><Card><div className="flex flex-wrap gap-4 items-end"><label className="text-sm text-slate-600">{t.subject}<select className="mt-1 block rounded-lg bg-[#e0e5eb] p-2" value={subject} onChange={e=>setSubject(e.target.value)}>{subjects.map(s=><option key={s}>{s}</option>)}</select></label><label className="text-sm text-slate-600">{t.iterations}<select className="mt-1 block rounded-lg bg-[#e0e5eb] p-2" value={iterations} onChange={e=>setIterations(Number(e.target.value))}><option value="1000">1 000</option><option value="2000">2 000</option><option value="10000">10 000</option></select></label><strong className="text-slate-700">{primary.rows.length} {t.predictions}</strong></div><p className="mt-4 text-sm text-slate-500">{t.backtestHelp}</p></Card>{!primary.metrics?<Card><p className="text-amber-800">{t.insufficient}</p></Card>:<><Card><h2 className="text-xl font-bold text-slate-700 mb-3">{t.notesgym}</h2><div className="grid grid-cols-2 lg:grid-cols-5 gap-3"><Metric label={t.mae} value={fmt(primary.metrics.mae)}/><Metric label={t.medianError} value={fmt(primary.metrics.medianAbsoluteError)}/><Metric label={t.bias} value={fmt(primary.metrics.bias)}/><Metric label={t.coverage} value={`${Math.round(primary.metrics.coverage*100)} %`}/><Metric label={t.width} value={fmt(primary.metrics.averageWidth)}/></div><p className="text-xs text-slate-500 mt-3">{t.metricsHelp}</p></Card><Card><div className="h-72"><ResponsiveContainer><AreaChart data={primary.rows}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="index"/><YAxis domain={[1,6]}/><Tooltip/><Area dataKey="p90" stroke="#94a3b8" fill="#cbd5e1"/><Area dataKey="p10" stroke="#94a3b8" fill="#e0e5eb"/><Line dataKey="predicted" stroke="#475569" dot={false}/><Line dataKey="actual" stroke="#0f766e"/></AreaChart></ResponsiveContainer></div></Card><ModelTable result={result} t={t}/><Card><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-sm"><thead><tr className="text-left text-slate-500">{[t.date,t.forecast,t.p10p90,t.actual,t.error].map(x=><th className="p-2" key={x}>{x}</th>)}</tr></thead><tbody>{primary.rows.map(r=><tr className="border-t border-slate-400/20" key={r.index}><td className="p-2">{r.date}</td><td>{fmt(r.predicted)}</td><td>{fmt(r.p10)}–{fmt(r.p90)}</td><td>{fmt(r.actual)}</td><td className={r.error>=0?"text-teal-700":"text-rose-700"}>{r.error>=0?"+":""}{fmt(r.error)}</td></tr>)}</tbody></table></div><p className="text-xs text-slate-500 mt-3">{t.errorHelp}</p></Card></>}</div>;
}
function ModelTable({result,t}){return <Card><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-sm"><thead><tr className="text-left text-slate-500"><th className="p-2">{t.parameters}</th><th>{t.mae}</th><th>{t.bias}</th><th>{t.coverage}</th><th>{t.width}</th></tr></thead><tbody>{[["notesgym",t.notesgym],["bootstrap",t.bootstrap],["baseline",t.baseline]].map(([key,label])=>{const m=result[key].metrics;return <tr key={key} className="border-t border-slate-400/20"><th className="p-2 text-left">{label}</th><td>{fmt(m?.mae)}</td><td>{fmt(m?.bias)}</td><td>{m?`${Math.round(m.coverage*100)} %`:"—"}</td><td>{fmt(m?.averageWidth)}</td></tr>})}</tbody></table></div></Card>}

export function SensitivityPanel({notes,t,gradingSystem}) {const subjects=[...new Set(notes.map(n=>String(n.matiere).trim()))].sort();const [subject,setSubject]=useState(subjects[0]||"");const [coefficient,setCoefficient]=useState(1);const [grade,setGrade]=useState(4);const currentSubject=weightedAverage(notes.filter(n=>String(n.matiere).trim()===subject));const currentGlobal=weightedAverage(notes);const point=sensitivityPoint(notes,subject,grade,coefficient);const curve=useMemo(()=>sensitivityCurve(notes,subject,coefficient),[notes,subject,coefficient]);const bounds=[curve[0]?.globalAverage,curve.at(-1)?.globalAverage];return <div className="space-y-5"><Card><div className="grid md:grid-cols-3 gap-4"><label>{t.subject}<select className="block w-full mt-1 p-2 rounded-lg bg-[#e0e5eb]" value={subject} onChange={e=>setSubject(e.target.value)}>{subjects.map(s=><option key={s}>{s}</option>)}</select></label><label>{t.coefficient}<input className="block w-full mt-1" type="range" min="0.25" max="5" step="0.25" value={coefficient} onChange={e=>setCoefficient(Number(e.target.value))}/><span>{coefficient}</span></label><label>{t.hypothetical}<input className="block w-full mt-1" type="range" min="1" max="6" step="0.05" value={grade} onChange={e=>setGrade(Number(e.target.value))}/><span>{formatGrade(grade,gradingSystem)}</span></label></div><p className="text-xs text-slate-500 mt-4">{t.sensitivityHelp}</p></Card><div className="grid md:grid-cols-3 gap-4"><Metric label={t.subjectAverage} value={`${formatGrade(currentSubject,gradingSystem)} → ${formatGrade(point.subjectAverage,gradingSystem)}`}/><Metric label={t.globalAverage} value={`${formatGrade(currentGlobal,gradingSystem)} → ${formatGrade(point.globalAverage,gradingSystem)}`}/><Metric label={t.compensation} value={`${point.compensation>=0?"+":""}${fmt(point.compensation)}`}/></div><Card><p className="text-sm text-slate-600 mb-2">{t.range}: {formatGrade(bounds[0],gradingSystem)}–{formatGrade(bounds[1],gradingSystem)}</p><div className="h-72"><ResponsiveContainer><LineChart data={curve}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="grade"/><YAxis domain={["dataMin-.1","dataMax+.1"]}/><Tooltip/><Line dataKey="globalAverage" stroke="#0f766e" dot={false}/><Line dataKey="subjectAverage" stroke="#475569" dot={false}/></LineChart></ResponsiveContainer></div></Card></div>}

export function PlaygroundPanel({notes,t}){const defaults=ANALYTICS_CONFIG.predictive;const [params,setParams]=useState({...defaults});const [iterations,setIterations]=useState(2000);const [seed,setSeed]=useState(482917);const subjects=[...new Set(notes.map(n=>String(n.matiere).trim()))].sort();const [subject,setSubject]=useState(subjects[0]||"");const history=notes.filter(n=>String(n.matiere).trim()===subject);const current=useMemo(()=>buildPredictiveDistribution(history,{iterations,seed,parameters:params}),[history,iterations,seed,params]);const standard=useMemo(()=>buildPredictiveDistribution(history,{iterations,seed}),[history,iterations,seed]);const slider=(key,label,max=1,step=.01)=><label className="block text-sm">{label}<input className="w-full" type="range" min="0" max={max} step={step} value={params[key]} onChange={e=>setParams({...params,[key]:Number(e.target.value)})}/><span>{params[key]}</span></label>;return <div className="grid lg:grid-cols-2 gap-5"><Card><label>{t.subject}<select className="ml-2 p-2 rounded-lg bg-[#e0e5eb]" value={subject} onChange={e=>setSubject(e.target.value)}>{subjects.map(s=><option key={s}>{s}</option>)}</select></label><h2 className="font-bold text-slate-700 my-4">{t.parameters}</h2><div className="space-y-4">{slider("historicalWeight",t.historicalWeight)}{slider("recentWeight",t.recentWeight)}{slider("trendWeight",t.trendWeight)}{slider("minimumSpread",t.minimumSpread,1,.05)}<label>{t.iterations}<input type="number" min="100" max="20000" className="ml-2 w-28 p-2 rounded-lg bg-[#e0e5eb]" value={iterations} onChange={e=>setIterations(Math.max(100,Math.min(20000,Number(e.target.value)||100)))}/></label><label className="block">{t.seed}<input type="number" className="ml-2 w-32 p-2 rounded-lg bg-[#e0e5eb]" value={seed} onChange={e=>setSeed(Number(e.target.value)||0)}/></label></div><p className="text-xs text-slate-500 my-3">{t.normalization}</p><div className="flex gap-2"><button className="rounded-xl px-4 py-2 shadow" onClick={()=>setParams({...defaults})}>{t.reset}</button><button className="rounded-xl px-4 py-2 shadow" onClick={()=>setSeed(s=>(s*1664525+1013904223)>>>0)}>{t.newSeed}</button></div></Card><Card><h2 className="font-bold text-slate-700 mb-4">{t.defaultParameters} / {t.playgroundCurrent}</h2>{!current?<p>{t.insufficient}</p>:<div className="grid grid-cols-3 gap-3"><span></span><b>{t.notesgym}</b><b>{t.playgroundCurrent}</b><span>{t.median}</span><span>{fmt(standard.median)}</span><span>{fmt(current.median)}</span><span>P10</span><span>{fmt(standard.interval[0])}</span><span>{fmt(current.interval[0])}</span><span>P90</span><span>{fmt(standard.interval[1])}</span><span>{fmt(current.interval[1])}</span></div>}</Card></div>}

export function DistributionPanel({notes,t}){const subjects=[...new Set(notes.map(n=>String(n.matiere).trim()))].sort();const [subject,setSubject]=useState(subjects[0]||"");const selected=notes.filter(n=>String(n.matiere).trim()===subject);const stats=descriptiveStats(selected);const normal=buildPredictiveDistribution(selected,{iterations:2000,seed:482917});const boot=bootstrapDistribution(selected,{iterations:2000,seed:482917});const bins=Array.from({length:10},(_,i)=>{const min=1+i*.5,max=min+.5;const count=a=>a?.filter(v=>v>=min&&(i===9?v<=max:v<max)).length||0;return {grade:(min+.25).toFixed(2),observed:selected.filter(n=>Number(n.note)>=min&&(i===9?Number(n.note)<=max:Number(n.note)<max)).length,notesgym:count(normal?.samples)/200,bootstrap:count(boot?.samples)/200}});return <div className="space-y-5"><Card><label>{t.subject}<select className="ml-2 p-2 rounded-lg bg-[#e0e5eb]" value={subject} onChange={e=>setSubject(e.target.value)}>{subjects.map(s=><option key={s}>{s}</option>)}</select></label>{selected.length<5&&<p className="mt-3 text-sm text-amber-800">{t.weakSample}</p>}<div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-4"><Metric label={t.count} value={stats.count}/><Metric label={t.mean} value={fmt(stats.average)}/><Metric label={t.median} value={fmt(stats.median)}/><Metric label={t.deviation} value={fmt(stats.standardDeviation)}/></div></Card><Card><div className="h-80"><ResponsiveContainer><ComposedChart data={bins}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="grade"/><YAxis/><Tooltip/><Legend/><Bar dataKey="observed" fill="#475569"/><Line dataKey="notesgym" stroke="#0f766e"/><Line dataKey="bootstrap" stroke="#b45309"/></ComposedChart></ResponsiveContainer></div><p className="text-sm text-slate-500 mt-3">{t.distributionHelp}</p></Card></div>}
